using System;
using System.ComponentModel.DataAnnotations;

namespace DemoProject.Services.ViewModel.Management.Conference
{
    public class MeetingAgendaViewModel
    {
        // MeetingAgenda

        public int PrmKey { get; set; }

        public Guid MeetingAgendaId { get; set; }

        public int MeetingPrmKey { get; set; }

        public int AgendaPrmKey { get; set; }

        public short SequenceNumber { get; set; }

        public bool IsAutoGenerated { get; set; }

        [StringLength(50)]
        public string SuggestiveMemberNumber { get; set; }

        [StringLength(50)]
        public string PermissiveMemberNumber { get; set; }

        [StringLength(1500)]
        public string Note { get; set; }

        [StringLength(3)]
        public string EntryStatus { get; set; }

        // MeetingAgendaMakerChecker

        public DateTime EntryDateTime { get; set; }

        public int MeetingAgendaPrmKey { get; set; }

        public short UserProfilePrmKey { get; set; }

        [StringLength(3)]
        public string UserAction { get; set; }

        [StringLength(1500)]
        public string Remark { get; set; }

        // Other

        // DropDown 
        public Guid MeetingId { get; set; }

        public string NameOfMeeting { get; set; } 

        public Guid AgendaId { get; set; } 

        public string NameOfAgenda { get; set; } 
    }
}
