using DemoProject.Domain.Entities.Management.Master;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DemoProject.Domain.Entities.Management.Conference
{
    [Table("MeetingAgenda")]
    public partial class MeetingAgenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingAgenda()
        {
            MeetingAgendaMakerCheckers = new HashSet<MeetingAgendaMakerChecker>();
            MinuteOfMeetingAgendas = new HashSet<MinuteOfMeetingAgenda>();
            //MinuteOfMeetingAgendaSpokespeople = new HashSet<MinuteOfMeetingAgendaSpokesperson>();
        }

        [Key]
        public int PrmKey { get; set; }

        public Guid MeetingAgendaId { get; set; }

        public int MeetingPrmKey { get; set; }

        public int AgendaPrmKey { get; set; }

        public short SequenceNumber { get; set; }

        public bool IsAutoGenerated { get; set; }

        [Required]
        [StringLength(50)]
        public string SuggestiveMemberNumber { get; set; }

        [Required]
        [StringLength(50)]
        public string PermissiveMemberNumber { get; set; }

        [Required]
        [StringLength(1500)]
        public string Note { get; set; }

        [Required]
        [StringLength(3)]
        public string EntryStatus { get; set; }

        public virtual Meeting Meeting { get; set; }

        public virtual Agenda Agenda { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingAgendaMakerChecker> MeetingAgendaMakerCheckers { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinuteOfMeetingAgenda> MinuteOfMeetingAgendas { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<MinuteOfMeetingAgendaSpokesperson> MinuteOfMeetingAgendaSpokespeople { get; set; }
    }
}
